#!/bin/bash

# Quick solution: Retry npm run dev and ignore ECONNRESET
# The tunnel is created BEFORE the error occurs

echo "🔧 IconTran - Workaround for ECONNRESET"
echo "======================================="
echo ""
echo "💡 SOLUTION:"
echo ""
echo "The error 'ECONNRESET' happens AFTER tunnel is created."
echo "Your app is still accessible via the tunnel URL!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📝 STEPS TO TEST APP:"
echo ""
echo "1. Run: npm run dev"
echo ""
echo "2. Look for this line (appears BEFORE error):"
echo "   └ Using URL: https://...trycloudflare.com"
echo "   ^^^^^^^^^ THIS IS YOUR APP URL"
echo ""
echo "3. Ignore the ECONNRESET error"
echo "   (App is already running!)"
echo ""
echo "4. Access app via Shopify Admin:"
echo "   → https://admin.shopify.com/store/YOUR_STORE/apps"
echo "   → Click [STAGING] Transcy"
echo "   → App should load (using tunnel URL)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⚠️  IF APP DOESN'T LOAD:"
echo ""
echo "Option A: Update Partner Dashboard with tunnel URL"
echo "   1. Copy tunnel URL from terminal"
echo "   2. Go to: https://partners.shopify.com/"
echo "   3. Apps → IconTrans → Configuration"
echo "   4. Update:"
echo "      - App URL: [paste tunnel URL]"
echo "      - Redirect URL: [tunnel URL]/api/auth"
echo ""
echo "Option B: Use ngrok (more stable)"
echo "   ./scripts/dev-with-ngrok.sh"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
read -p "Press ENTER to run npm run dev now..."

npm run dev
