#!/bin/bash

# Get Shopify API Secret - Manual Guide
# Use this when Shopify CLI cannot login

echo "🔑 How to Get SHOPIFY_API_SECRET"
echo "=================================="
echo ""
echo "Vì Shopify CLI không login được (VPN/firewall), bạn cần:"
echo ""
echo "📋 Steps:"
echo ""
echo "1. Mở Shopify Partner Dashboard"
echo "   → https://partners.shopify.com/"
echo ""
echo "2. Click vào Apps → IconTrans (hoặc [STAGING] Transcy)"
echo ""
echo "3. Trong App Details page:"
echo "   → Click tab 'Configuration'"
echo "   → Scroll xuống 'Client credentials'"
echo ""
echo "4. Copy 'API secret key'"
echo "   (Nếu chưa có, click 'Reset client credentials')"
echo ""
echo "5. Update .env file:"
echo "   → Mở: .env"
echo "   → Sửa dòng: SHOPIFY_API_SECRET=your_api_secret_here"
echo "   → Thay bằng: SHOPIFY_API_SECRET=<secret_key_vừa_copy>"
echo ""
echo "6. Save file và restart server"
echo "   → npm start"
echo ""
echo "✅ Sau đó app sẽ hoạt động bình thường!"
echo ""
echo "📌 Note:"
echo "   - API Key đã được sync: e6200abaeadc253dab4d28ee71b3fdfb"
echo "   - Chỉ cần API Secret là có thể chạy"
echo "   - KHÔNG CẦN Shopify CLI login"
echo ""
