#!/bin/bash

echo "🚀 RESTART SHOPIFY DEV + VERIFY URLs"
echo "============================================"
echo ""
echo "1. Stop current dev server..."
echo "   Press Ctrl+C in terminal running 'npm run dev'"
echo ""
echo "2. Then run:"
echo "   npm run dev"
echo ""
echo "3. Wait for output:"
echo "   ✓ Using URL: https://...trycloudflare.com"
echo "   ✓ Synced configuration to partners.shopify.com"
echo ""
echo "4. Verify shopify.app.toml updated:"
echo "   cat shopify.app.toml | grep application_url"
echo ""
echo "5. Uninstall + Reinstall app:"
echo "   Shopify Admin → Apps → IconTrans → Uninstall"
echo "   Then reinstall from Apps list"
echo ""
echo "============================================"
echo "EXPECTED RESULT after reinstall:"
echo "  ✅ Loading screen 'Welcome to Transcy!'"
echo "  ✅ Progress bar 0% → 100%"
echo "  ✅ 5 animated steps"
echo "  ✅ Auto redirect to onboarding"
echo "  ✅ Select plan (Free/Basic/Pro/Enterprise)"
echo "============================================"
echo ""
echo "If you still see 'Example Domain':"
echo "1. Check URL in terminal output"
echo "2. Manually update Partner Dashboard:"
echo "   partners.shopify.com → Apps → IconTrans → Configuration"
echo "   Update 'App URL' and 'Redirect URLs' with tunnel URL"
echo "============================================"
